import { chromium } from '/opt/npm-tools/node_modules/playwright/index.mjs';
const [out] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5173/');
await page.waitForTimeout(600);
await page.mouse.click(420, 200);
await page.waitForTimeout(500);
await page.locator('#hangar button', { hasText: 'TECH TREE' }).click();
await page.waitForTimeout(500);
await page.locator('.vcard', { hasText: 'M4A3 (76) W' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/p1_detail.png` });
await page.locator('.modal button', { hasText: 'Research' }).click();
await page.waitForTimeout(300);
console.log('researching:', await page.evaluate(() => window.__pen.save().researching));
// fake a battle win worth enough RP
await page.locator('#tree .topbar .icon-btn').click();
await page.waitForTimeout(300);
await page.evaluate(() => { window.__pen.save().settings.map = 'city'; });
await page.evaluate(() => window.__pen.startBattle());
await page.waitForTimeout(1500);
await page.evaluate(() => { const b = window.__pen.battle; for (let i = 0; i < 12; i++) b.addReward('Target destroyed', 330, 1650); b.stats.kills = 12; b.end('victory'); });
await page.waitForTimeout(4200);
await page.screenshot({ path: `${out}/p2_results.png` });
const s1 = await page.evaluate(() => { const s = window.__pen.save(); return { researched: s.researched, researching: s.researching, rpFree: s.rpFree, credits: s.credits }; });
console.log('after battle:', JSON.stringify(s1));
await page.getByText('Continue').click();
await page.waitForTimeout(500);
await page.locator('#hangar button', { hasText: 'TECH TREE' }).click();
await page.waitForTimeout(500);
await page.locator('.vcard', { hasText: 'M4A3 (76) W' }).click();
await page.waitForTimeout(300);
await page.locator('.modal button', { hasText: 'Buy' }).click();
await page.waitForTimeout(400);
const s2 = await page.evaluate(() => { const s = window.__pen.save(); return { owned: s.owned, lineup: s.lineup, credits: s.credits }; });
console.log('after buy:', JSON.stringify(s2));
await page.screenshot({ path: `${out}/p3_tree.png` });
// remove from lineup and add M24
await page.locator('.vcard', { hasText: 'M24 Chaffee' }).click();
await page.waitForTimeout(300);
const txt = await page.locator('.modal').innerText();
console.log('M24 modal buttons:', txt.split('\n').filter(l => /lineup|hangar/i.test(l)).join(' | '));
await browser.close();
