import { chromium } from '/opt/npm-tools/node_modules/playwright/index.mjs';
const [out] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5173/');
await page.waitForTimeout(500);
await page.evaluate(() => { const s = window.__pen.save(); s.researched.push('su85', 't3485'); s.owned.push('t3485'); s.research['is1'] = 2600; s.researching = 'is1'; });
await page.mouse.click(420, 200);
await page.waitForTimeout(400);
await page.evaluate(() => { window.__pen.show('tree'); });
await page.waitForTimeout(300);
await page.locator('.tree-tabs button', { hasText: 'USSR' }).click();
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/tree_ussr.png` });
await page.locator('.tree-scroll').evaluate((el) => el.scrollLeft = 400);
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/tree_ussr_scrolled.png` });
await browser.close();
